apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy-service
spec:
  selector:
    app: nginx-reverse-proxy
  ports:
    - protocol: TCP
      port: 7071
      targetPort: 7071
  type: ClusterIP # Change this as per your requirement (ClusterIP, NodePort, LoadBalancer, etc.)

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-reverse-proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-reverse-proxy
  template:
    metadata:
      labels:
        app: nginx-reverse-proxy
    spec:
      containers:
        - name: nginx-reverse-proxy
          image: ojoxdan/pulsar-nginx-proxy # Replace with your custom Docker image
          ports:
            - containerPort: 7071
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-configmap
            items:
              - key: nginx.conf
                path: nginx.conf
