apiVersion: apps/v1
kind: Deployment
metadata:
  name: pulsar-nginx-proxy-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pulsar-nginx-proxy
  template:
    metadata:
      labels:
        app: pulsar-nginx-proxy
    spec:
      containers:
        - name: pulsar-nginx-proxy-container
          image: ojoxdan/pulsar-nginx-proxy:latest
          ports:
            - containerPort: 7071

---
apiVersion: v1
kind: Service
metadata:
  name: pulsar-nginx-proxy-service
spec:
  selector:
    app: pulsar-nginx-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7071
  type: LoadBalancer
